"""update the transcription table

Revision ID: 3c2a559dc250
Revises: 80825b9c149e
Create Date: 2026-03-25 12:53:35.750110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c2a559dc250'
down_revision: Union[str, Sequence[str], None] = '80825b9c149e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transcript_responses', sa.Column('client_name', sa.String(), nullable=True))
    op.add_column('transcript_responses', sa.Column('client_number', sa.String(), nullable=True))
    op.add_column('transcript_responses', sa.Column('policy_type', sa.String(), nullable=True))
    op.add_column('transcript_responses', sa.Column('reason_for_call', sa.Text(), nullable=True))
    op.add_column('transcript_responses', sa.Column('key_points', sa.Text(), nullable=True))
    op.add_column('transcript_responses', sa.Column('customer_sentiment', sa.String(), nullable=True))
    op.add_column('transcript_responses', sa.Column('follow_up_needed', sa.Boolean(), nullable=True))
    op.add_column('transcript_responses', sa.Column('follow_up_task', sa.Text(), nullable=True))
    op.add_column('transcript_responses', sa.Column('crm_note', sa.Text(), nullable=True))
    op.add_column('transcript_responses', sa.Column('recordingID', sa.String(), nullable=True))
    op.add_column('transcript_responses', sa.Column('created_at', sa.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transcript_responses', 'created_at')
    op.drop_column('transcript_responses', 'recordingID')
    op.drop_column('transcript_responses', 'crm_note')
    op.drop_column('transcript_responses', 'follow_up_task')
    op.drop_column('transcript_responses', 'follow_up_needed')
    op.drop_column('transcript_responses', 'customer_sentiment')
    op.drop_column('transcript_responses', 'key_points')
    op.drop_column('transcript_responses', 'reason_for_call')
    op.drop_column('transcript_responses', 'policy_type')
    op.drop_column('transcript_responses', 'client_number')
    op.drop_column('transcript_responses', 'client_name')
    # ### end Alembic commands ###
