"""add agency_zoom_task_ids column

Revision ID: 7eefdafb1b46
Revises: 82e2e373c4eb
Create Date: 2026-04-03 17:29:37.814478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7eefdafb1b46'
down_revision: Union[str, Sequence[str], None] = '82e2e373c4eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transcript_responses', sa.Column('agency_zoom_task_ids', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transcript_responses', 'agency_zoom_task_ids')
    # ### end Alembic commands ###
