"""create transcripton table

Revision ID: 80825b9c149e
Revises: f4cd45c07a1c
Create Date: 2026-03-24 12:59:18.404378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80825b9c149e'
down_revision: Union[str, Sequence[str], None] = 'f4cd45c07a1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transcript_responses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('file_link', sa.String(), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', name='transcriptstatus'), nullable=False),
    sa.Column('transcription', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transcript_responses_id'), 'transcript_responses', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transcript_responses_id'), table_name='transcript_responses')
    op.drop_table('transcript_responses')
    # ### end Alembic commands ###
