"""add analysis field

Revision ID: e6670002ea38
Revises: 956c056e6f77
Create Date: 2026-04-16 17:59:22.058005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6670002ea38'
down_revision: Union[str, Sequence[str], None] = '956c056e6f77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transcript_responses', sa.Column('insured_intent', sa.Text(), nullable=True))
    op.add_column('transcript_responses', sa.Column('material_risk_facts', sa.Text(), nullable=True))
    op.add_column('transcript_responses', sa.Column('coverage_discussed', sa.Text(), nullable=True))
    op.add_column('transcript_responses', sa.Column('monetary_values', sa.Text(), nullable=True))
    op.add_column('transcript_responses', sa.Column('options_presented', sa.Text(), nullable=True))
    op.add_column('transcript_responses', sa.Column('client_selection', sa.Text(), nullable=True))
    op.add_column('transcript_responses', sa.Column('agent_recommendation', sa.Text(), nullable=True))
    op.add_column('transcript_responses', sa.Column('eo_red_flags', sa.Text(), nullable=True))
    op.add_column('transcript_responses', sa.Column('agent_statements_liability', sa.Text(), nullable=True))
    op.add_column('transcript_responses', sa.Column('missing_information', sa.Text(), nullable=True))
    op.add_column('transcript_responses', sa.Column('confidence_score', sa.Integer(), nullable=True))
    # op.drop_column('webhook_state', 'schedule_interval_seconds')
    op.execute(
        "ALTER TABLE webhook_state DROP COLUMN IF EXISTS schedule_interval_seconds"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('webhook_state', sa.Column('schedule_interval_seconds', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('transcript_responses', 'confidence_score')
    op.drop_column('transcript_responses', 'missing_information')
    op.drop_column('transcript_responses', 'agent_statements_liability')
    op.drop_column('transcript_responses', 'eo_red_flags')
    op.drop_column('transcript_responses', 'agent_recommendation')
    op.drop_column('transcript_responses', 'client_selection')
    op.drop_column('transcript_responses', 'options_presented')
    op.drop_column('transcript_responses', 'monetary_values')
    op.drop_column('transcript_responses', 'coverage_discussed')
    op.drop_column('transcript_responses', 'material_risk_facts')
    op.drop_column('transcript_responses', 'insured_intent')
    # ### end Alembic commands ###
