"""update the token id

Revision ID: f4cd45c07a1c
Revises: 82212325d436
Create Date: 2026-03-23 18:43:51.842632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4cd45c07a1c'
down_revision: Union[str, Sequence[str], None] = '82212325d436'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_tokens_token_id'), table_name='users_tokens')
    op.create_index(op.f('ix_users_tokens_token_id'), 'users_tokens', ['token_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_tokens_token_id'), table_name='users_tokens')
    op.create_index(op.f('ix_users_tokens_token_id'), 'users_tokens', ['token_id'], unique=False)
    # ### end Alembic commands ###
